language: node_js
node_js:
- 0.10
before_script:
  - npm install grunt-cli -g
  - grunt build
  - npm install browserstack-runner 
script:
  - grunt travis --verbose
  - node ./node_modules/.bin/browserstack-runner
env:
  global:
  - BROWSERSTACK_USERNAME=dhimil
  - secure: "MjhPBwsIrpNFkSaObqu8WlJpX2Z19o1PVu8tZx378ZQZnTg0QVSCaQrlgox8dvlEeHNlS6193BGU5y0iMC4f4XLNIBj2dwnTr8oEDqGahPryLfzlU5KaTYyfjeH080cnQOyjUJ1rS/zPLMBwqK44BPvvnG234qORqheF/n62vqA="
  - secure: noRIQS5Wv/9SFs4bK+0NZNQ7nnL+WfP6PhkPQR5QxNmXR1S4wjdiHy4/yv4aO/j1URgFw1YiFf+80k7YIn/9vIT+lMzE0wiw5FXTQM9PIB2mPHC2wzc0Y1Xj5kfuFXZemWTt73y1IkT53PjxezslVSduPKTxjXJuPmUk2FG3yaw=
  - secure: QUDo7NDflY7K3xrBfcjVmhz6IBKoMOiosABbOEdQo1PiqAa8JBbjd+h02p6k+ZNQNymB1EcBhe20O1dMJYOg2E9BB8vtCsJtXTw1TEKlEwUVPUMkAtP6gpOk8XfmP9o6Ej2uM89+r6vLTDJIH1FPSwYbyxvWzIEi52gjFZUN6Mw=
